- name: "documentation"
  description: "Improvements or additions to documentation"
  color: 0075ca
- name: "bug-P1"
  description: "Highest rated bug or issue, affects all"
  color: b23128
- name: "bug-P2"
  description: "Medium rated bug, affects a few"
  color: de3d32
- name: "bug-P3"
  description: "Lowest rated bug, affects nearly none or low-impact"
  color: f44336
- name: "feature"
  description: "Any new significant addition"
  color: 0e8a16
- name: "hot-fix"
  description: "Urgent or important fix/patch"
  color: b60205
- name: "idea"
  description: "Any idea, suggestion"
  color: cccccc
- name: "prototype"
  description: "Experimental - can break!"
  color: d4c5f9
- name: "question"
  description: "Any question or concern"
  color: cc317c
- name: "test"
  description: "Unit tests, mocking, integration testing"
  color: c2e0c6
- name: "ui-ux"
  description: "Anything GUI related"
  color: fbca04
- name: "chore"
  description: "Simple dependency updates or version bumps"
  color: 006b75
- name: "dependencies"
  description: "Dependency updates, version bumps, etc."
  color: 006b75
- name: "update"
  description: "General updates"
  color: 006b75
- name: "refactor"
  description: "Any significant refactoring"
  color: FFA500
- name: "automerge"
  description: "Used for automatic merging"
  color: FEF2C0
- name: "work-in-progress"
  description: "Used for denoting a WIP, stops auto-merge"
  color: FBCA04
- name: "stale"
  description: "Old, unused, stale"
  color: c2e0c6
- name: "gomod"
  description: "Used for referencing Go Modules"
  color: 006b75
- name: "github-actions"
  description: "Used for referencing GitHub Actions"
  color: 006b75
- name: "devcontainer"
  description: "Used for referencing DevContainers"
  color: 006b75
- name: "docker"
  description: "Used for referencing Docker related issues"
  color: 006b75
